### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by mirelsen** [redmusicxd/iptv_frontend#1]
Salutare!
Scuze de deranj, dar un mic "howto" ar fii de foarte mare ajutor... le-am sucit pe toate partile, nu-mi iese...
Multumiri!

**Comment by rednblkx** [comment]
Salutare!

Nu intentiam neaparat sa fie folosit de cineva, a fost doar "o idee de weekend".

Trebuie doar sa rulezi `npm install`, sa creezi un fisier `.env` unde introduci `VITE_API_BASE_URL=<http(s)://[domeniu/adresa ip iptvro_v2]:[port]>`(fara <>,(),[]) si dupa rulezi `npm run build` iar in urma asta un folder `dist` va fi creat unde se afla fisierele care trebuie sa le uploadezi pe webserver, daca ai probleme de 404 si probabil o sa ai daca folosesti un simplu apache sau nginx, cauta despre SPA Routing <insert http server name> sau react router <insert http server name> ca chiar n-am chef de asemenea debugging.

Cheers!
